"""
Insight model — output from the agent pipeline (InsightAgent).
Stores human-readable findings about developers and teams.
"""

from sqlalchemy import Column, String, ForeignKey, Index, Numeric, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID, JSONB
import uuid
from app.models.base import BaseModel


class Insight(BaseModel):
    """
    An Insight is a finding generated by the agent pipeline.
    - developer_id is nullable (null = team-level insight)
    - metadata stores arbitrary JSON context
    """
    __tablename__ = "insights"

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )

    agent_run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agent_runs.id", ondelete="CASCADE"),
        nullable=False,
    )

    developer_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("developers.id", ondelete="SET NULL"),
        nullable=True,
        comment="Null if this is a team-level insight"
    )

    insight_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="health_score | burnout_risk | quality_regression | team_summary"
    )

    severity: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="info",
        comment="info | warning | critical"
    )

    title: Mapped[str] = mapped_column(String(500), nullable=False)

    body: Mapped[str] = mapped_column(Text, nullable=False)

    score: Mapped[float | None] = mapped_column(
        Numeric(precision=5, scale=2),
        nullable=True,
        comment="0-100 health score (null for non-score insight types)"
    )

    metadata: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # Relationships
    tenant = relationship("Tenant", back_populates="insights")
    agent_run = relationship("AgentRun", back_populates="insights")
    developer = relationship("Developer", back_populates="insights")
    actions = relationship("AgentAction", back_populates="insight")

    __table_args__ = (
        Index("idx_insights_tenant_run", "tenant_id", "agent_run_id"),
        Index("idx_insights_developer", "developer_id"),
        Index("idx_insights_severity", "severity"),
    )
