# TODO: app/providers/gitlab.py — implement GitLabProvider(VCSProvider) when adding GitLab support
from typing import Protocol, runtime_checkable
from datetime import datetime

@runtime_checkable
class VCSProvider(Protocol):
    async def get_commits(self, repo_full_name: str, since: datetime, until: datetime) -> list[dict]: ...
    async def get_pull_requests(self, repo_full_name: str, since: datetime) -> list[dict]: ...
    async def get_org_repos(self, org_name: str) -> list[dict]: ...
    async def get_user_info(self, access_token: str) -> dict: ...
    async def validate_webhook(self, payload: bytes, signature: str) -> bool: ...
